//
// (c) 2026 Eduardo Doria.
//

#include "DoriaxGLFW.h"

#include <math.h>

#include "Engine.h"
#include "GamepadMappings.h"

#ifndef DORIAX_VSYNC_ENABLED
#define DORIAX_VSYNC_ENABLED 1
#endif

// 0 = windowed, 1 = maximized, 2 = fullscreen
#ifndef DORIAX_WINDOW_MODE
#define DORIAX_WINDOW_MODE 0
#endif

#ifndef DORIAX_WINDOW_RESIZABLE
#define DORIAX_WINDOW_RESIZABLE 1
#endif

#ifndef DORIAX_WINDOW_TITLE
#define DORIAX_WINDOW_TITLE "Doriax"
#endif

#ifndef DORIAX_APP_ID
#define DORIAX_APP_ID "Doriax"
#endif

#ifdef DORIAX_WINDOW_ICON
// Generated by the editor export into the project root (on the include path)
#include "app_icon.h"
#endif

int DoriaxGLFW::windowPosX;
int DoriaxGLFW::windowPosY;
int DoriaxGLFW::windowWidth;
int DoriaxGLFW::windowHeight;  

int DoriaxGLFW::screenWidth;
int DoriaxGLFW::screenHeight;

double DoriaxGLFW::mousePosX;
double DoriaxGLFW::mousePosY;

int DoriaxGLFW::sampleCount;

GLFWwindow* DoriaxGLFW::window;
GLFWmonitor* DoriaxGLFW::monitor;

DoriaxGLFW::GamepadState DoriaxGLFW::gamepads[GLFW_JOYSTICK_LAST + 1];


DoriaxGLFW::DoriaxGLFW(){

}

void DoriaxGLFW::pollGamepads(){
    for (int jid = 0; jid <= GLFW_JOYSTICK_LAST; jid++){
        GamepadState& state = gamepads[jid];

        GLFWgamepadstate glfwState;
        bool connected = glfwJoystickPresent(jid) && glfwGetGamepadState(jid, &glfwState);

        if (connected && !state.connected){
            state = GamepadState();
            state.connected = true;
            // triggers rest at -1; seed so a resting trigger doesn't emit a
            // spurious axis move from 0 to -1 on connect
            state.axes[GLFW_GAMEPAD_AXIS_LEFT_TRIGGER] = -1.0f;
            state.axes[GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER] = -1.0f;
            const char* name = glfwGetGamepadName(jid);
            doriax::Engine::systemGamepadConnect(jid, name ? name : "Gamepad");
        }else if (!connected && state.connected){
            state = GamepadState();
            doriax::Engine::systemGamepadDisconnect(jid);
        }

        if (!connected)
            continue;

        for (int button = 0; button <= GLFW_GAMEPAD_BUTTON_LAST; button++){
            if (glfwState.buttons[button] != state.buttons[button]){
                state.buttons[button] = glfwState.buttons[button];
                if (glfwState.buttons[button] == GLFW_PRESS){
                    doriax::Engine::systemGamepadButtonDown(jid, button);
                }else{
                    doriax::Engine::systemGamepadButtonUp(jid, button);
                }
            }
        }

        for (int axis = 0; axis <= GLFW_GAMEPAD_AXIS_LAST; axis++){
            if (fabsf(glfwState.axes[axis] - state.axes[axis]) > 0.001f){
                state.axes[axis] = glfwState.axes[axis];
                doriax::Engine::systemGamepadAxisMove(jid, axis, glfwState.axes[axis]);
            }
        }
    }
}

int DoriaxGLFW::init(int argc, char **argv){
    windowWidth = DEFAULT_WINDOW_WIDTH;
    windowHeight = DEFAULT_WINDOW_HEIGHT;

    sampleCount = 1;

    doriax::Engine::systemInit(argc, argv, new DoriaxGLFW());

    /* create window and GL context via GLFW */
    glfwInit();

    // GLFW's built-in gamepad database misses controllers newer than its
    // release; without a mapping glfwGetGamepadState fails and the pad is
    // treated as disconnected. Apply the community database over it.
    for (size_t i = 0; i < DORIAX_GAMEPAD_MAPPINGS_COUNT; i++)
        glfwUpdateGamepadMappings(DORIAX_GAMEPAD_MAPPINGS[i]);

    glfwWindowHint(GLFW_SAMPLES, (sampleCount == 1) ? 0 : sampleCount);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GLFW_TRUE);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_RESIZABLE, DORIAX_WINDOW_RESIZABLE ? GLFW_TRUE : GLFW_FALSE);

    // Identify the window to the desktop environment so it can be matched to
    // an installed <app_id>.desktop entry (Wayland shows the app icon ONLY
    // through that association; X11 uses the class as a fallback for grouping).
#ifdef GLFW_X11_CLASS_NAME
    glfwWindowHintString(GLFW_X11_CLASS_NAME, DORIAX_APP_ID);
    glfwWindowHintString(GLFW_X11_INSTANCE_NAME, DORIAX_APP_ID);
#endif
#ifdef GLFW_WAYLAND_APP_ID
    glfwWindowHintString(GLFW_WAYLAND_APP_ID, DORIAX_APP_ID);
#endif

    monitor = glfwGetPrimaryMonitor();

    // start fullscreen at the current desktop video mode; fall back to windowed
    // when the monitor or its video mode is unavailable (e.g. headless session)
    const GLFWvidmode* videoMode = nullptr;
    if (DORIAX_WINDOW_MODE == 2 && monitor)
        videoMode = glfwGetVideoMode(monitor);

    if (videoMode) {
        glfwWindowHint(GLFW_RED_BITS, videoMode->redBits);
        glfwWindowHint(GLFW_GREEN_BITS, videoMode->greenBits);
        glfwWindowHint(GLFW_BLUE_BITS, videoMode->blueBits);
        glfwWindowHint(GLFW_REFRESH_RATE, videoMode->refreshRate);
        window = glfwCreateWindow(videoMode->width, videoMode->height, DORIAX_WINDOW_TITLE, monitor, 0);
    } else {
        if (DORIAX_WINDOW_MODE == 1)
            glfwWindowHint(GLFW_MAXIMIZED, GLFW_TRUE);
        window = glfwCreateWindow(windowWidth, windowHeight, DORIAX_WINDOW_TITLE, 0, 0);
    }

    glfwMakeContextCurrent(window);
    glfwSwapInterval(DORIAX_VSYNC_ENABLED ? 1 : 0);

#ifdef DORIAX_WINDOW_ICON
    {
        // Window/taskbar icon on X11 and Windows. Wayland has no client-set
        // window icons (GLFW reports FeatureUnavailable and ignores the call);
        // the Windows executable additionally embeds the icon via app_icon.rc.
        GLFWimage iconImages[DORIAX_APP_ICON_COUNT];
        for (int i = 0; i < DORIAX_APP_ICON_COUNT; i++) {
            iconImages[i].width = DORIAX_APP_ICON_IMAGES[i].width;
            iconImages[i].height = DORIAX_APP_ICON_IMAGES[i].height;
            iconImages[i].pixels = const_cast<unsigned char*>(DORIAX_APP_ICON_IMAGES[i].pixels);
        }
        glfwSetWindowIcon(window, DORIAX_APP_ICON_COUNT, iconImages);
    }
#endif

    glfwSetMouseButtonCallback(window, [](GLFWwindow*, int btn, int action, int mods) {
        if (action==GLFW_PRESS){
            doriax::Engine::systemMouseDown(btn, float(mousePosX), float(mousePosY), mods);
        }else if (action==GLFW_RELEASE){
            doriax::Engine::systemMouseUp(btn, float(mousePosX), float(mousePosY), mods);
        }
    });
    glfwSetCursorPosCallback(window, [](GLFWwindow*, double pos_x, double pos_y) {
        float xscale, yscale;
        glfwGetWindowContentScale(window, &xscale, &yscale);

        mousePosX = pos_x * xscale;
        mousePosY = pos_y * yscale;
        doriax::Engine::systemMouseMove(float(mousePosX), float(mousePosY), 0);
    });
    glfwSetScrollCallback(window, [](GLFWwindow*, double xoffset, double yoffset){
        doriax::Engine::systemMouseScroll((float)xoffset, (float)yoffset, 0);
    });
    glfwSetKeyCallback(window, [](GLFWwindow*, int key, int /*scancode*/, int action, int mods){
        if (action==GLFW_PRESS){
            if (key == GLFW_KEY_TAB)
                doriax::Engine::systemCharInput('\t');
            if (key == GLFW_KEY_BACKSPACE)
                doriax::Engine::systemCharInput('\b');
            if (key == GLFW_KEY_ENTER)
                doriax::Engine::systemCharInput('\r');
            if (key == GLFW_KEY_ESCAPE)
                doriax::Engine::systemCharInput('\x1b');
            doriax::Engine::systemKeyDown(key, false, mods);
        }else if (action==GLFW_REPEAT){
            if (key == GLFW_KEY_TAB)
                doriax::Engine::systemCharInput('\t');
            if (key == GLFW_KEY_BACKSPACE)
                doriax::Engine::systemCharInput('\b');
            if (key == GLFW_KEY_ENTER)
                doriax::Engine::systemCharInput('\r');
            if (key == GLFW_KEY_ESCAPE)
                doriax::Engine::systemCharInput('\x1b');
            doriax::Engine::systemKeyDown(key, true, mods);
        }else if (action==GLFW_RELEASE){
            doriax::Engine::systemKeyUp(key, false, mods);
        }
    });
    glfwSetCharCallback(window, [](GLFWwindow*, unsigned int codepoint){
        doriax::Engine::systemCharInput(codepoint);
    });

    int cur_width, cur_height;
    glfwGetFramebufferSize(window, &cur_width, &cur_height);

    DoriaxGLFW::screenWidth = cur_width;
    DoriaxGLFW::screenHeight = cur_height;

    doriax::Engine::systemViewLoaded();
    doriax::Engine::systemViewChanged();

    /* draw loop */
    while (!glfwWindowShouldClose(window)) {
        int cur_width, cur_height;
        glfwGetFramebufferSize(window, &cur_width, &cur_height);

        if (cur_width != DoriaxGLFW::screenWidth || cur_height != DoriaxGLFW::screenHeight){
            DoriaxGLFW::screenWidth = cur_width;
            DoriaxGLFW::screenHeight = cur_height;
            doriax::Engine::systemViewChanged();
        }

        doriax::Engine::systemDraw();

        glfwSwapBuffers(window);
        glfwPollEvents();
        pollGamepads();
    }

    doriax::Engine::systemViewDestroyed();
    doriax::Engine::systemShutdown();
    glfwTerminate();
    return 0;
}

int DoriaxGLFW::getScreenWidth(){
    return DoriaxGLFW::screenWidth;
}

int DoriaxGLFW::getScreenHeight(){
    return DoriaxGLFW::screenHeight;
}

int DoriaxGLFW::getSampleCount(){
    return DoriaxGLFW::sampleCount;
}

bool DoriaxGLFW::isFullscreen(){
    return glfwGetWindowMonitor(window) != nullptr;
}

void DoriaxGLFW::requestFullscreen(){
    if (isFullscreen())
        return;

    // backup window position and window size
    glfwGetWindowPos(window, &windowPosX, &windowPosY);
    glfwGetWindowSize(window, &windowWidth, &windowHeight);
        
    // get resolution of monitor
    const GLFWvidmode * mode = glfwGetVideoMode(monitor);

    // switch to full screen
    glfwSetWindowMonitor(window, monitor, 0, 0, mode->width, mode->height, 0 );
}

void DoriaxGLFW::exitFullscreen(){
    if (!isFullscreen())
        return;

    // restore last window size and position
    glfwSetWindowMonitor(window, nullptr,  windowPosX, windowPosY, windowWidth, windowHeight, 0);
}

bool DoriaxGLFW::isWindowMaximized(){
    return glfwGetWindowAttrib(window, GLFW_MAXIMIZED) == GLFW_TRUE;
}

void DoriaxGLFW::maximizeWindow(){
    // GLFW ignores maximize on fullscreen windows
    glfwMaximizeWindow(window);
}

void DoriaxGLFW::restoreWindow(){
    glfwRestoreWindow(window);
}

void DoriaxGLFW::setWindowSize(int width, int height){
    if (width < 1 || height < 1)
        return;

    if (isFullscreen()){
        // keep the display mode; resize the window that exitFullscreen restores
        windowWidth = width;
        windowHeight = height;
        return;
    }

    glfwSetWindowSize(window, width, height);
}

bool DoriaxGLFW::isWindowResizable(){
    return glfwGetWindowAttrib(window, GLFW_RESIZABLE) == GLFW_TRUE;
}

void DoriaxGLFW::setWindowResizable(bool resizable){
    glfwSetWindowAttrib(window, GLFW_RESIZABLE, resizable ? GLFW_TRUE : GLFW_FALSE);
}

void DoriaxGLFW::setWindowTitle(const std::string& title){
    glfwSetWindowTitle(window, title.c_str());
}

void DoriaxGLFW::setMouseCursor(doriax::CursorType type){
    GLFWcursor* cursor = NULL;

    if (type == doriax::CursorType::ARROW){
        cursor = glfwCreateStandardCursor(GLFW_ARROW_CURSOR);
    }else if (type == doriax::CursorType::IBEAM){
        cursor = glfwCreateStandardCursor(GLFW_IBEAM_CURSOR);
    }else if (type == doriax::CursorType::CROSSHAIR){
        cursor = glfwCreateStandardCursor(GLFW_CROSSHAIR_CURSOR);
    }else if (type == doriax::CursorType::POINTING_HAND){
        #ifdef GLFW_POINTING_HAND_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_POINTING_HAND_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_HAND_CURSOR);
        #endif
    }else if (type == doriax::CursorType::RESIZE_EW){
        #ifdef GLFW_RESIZE_EW_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_RESIZE_EW_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_HRESIZE_CURSOR);
        #endif
    }else if (type == doriax::CursorType::RESIZE_NS){
        #ifdef GLFW_RESIZE_NS_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_RESIZE_NS_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_VRESIZE_CURSOR);
        #endif
    }else if (type == doriax::CursorType::RESIZE_NWSE){
        #ifdef GLFW_RESIZE_NWSE_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_RESIZE_NWSE_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_HRESIZE_CURSOR);
        #endif
    }else if (type == doriax::CursorType::RESIZE_NESW){
        #ifdef GLFW_RESIZE_NESW_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_RESIZE_NESW_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_HRESIZE_CURSOR);
        #endif
    }else if (type == doriax::CursorType::RESIZE_ALL){
        #ifdef GLFW_RESIZE_ALL_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_RESIZE_ALL_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_HRESIZE_CURSOR);
        #endif
    }else if (type == doriax::CursorType::NOT_ALLOWED){
        #ifdef GLFW_NOT_ALLOWED_CURSOR
        cursor = glfwCreateStandardCursor(GLFW_NOT_ALLOWED_CURSOR);
        #else
        cursor = glfwCreateStandardCursor(GLFW_ARROW_CURSOR);
        #endif
    }

    if (cursor) {
        glfwSetCursor(window, cursor);
    } else {
        // Handle error: cursor creation failed
    }
}

void DoriaxGLFW::setMouseMode(doriax::MouseMode mode){
    switch (mode){
        case doriax::MouseMode::NORMAL:
            glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
            break;
        case doriax::MouseMode::HIDDEN:
            glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_HIDDEN);
            break;
        case doriax::MouseMode::CAPTURED:
            glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);
            break;
        case doriax::MouseMode::CONFINED:
            // Keep the cursor visible but trapped inside the window (GLFW 3.4+).
            // Fall back to a free cursor where the capture mode isn't available.
#ifdef GLFW_CURSOR_CAPTURED
            glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_CAPTURED);
#else
            glfwSetInputMode(window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);
#endif
            break;
    }
}

void DoriaxGLFW::setMousePosition(float x, float y){
    float xscale, yscale;
    glfwGetWindowContentScale(window, &xscale, &yscale);

    mousePosX = x;
    mousePosY = y;
    glfwSetCursorPos(window, x / xscale, y / yscale);
}

std::string DoriaxGLFW::getAssetPath(){
    return "assets";
}

std::string DoriaxGLFW::getUserDataPath(){
    return ".";
}

std::string DoriaxGLFW::getLuaPath(){
    return "lua";
}
