//
// (c) 2026 Eduardo Doria.
//

#ifndef MODEL_COMPONENT_H
#define MODEL_COMPONENT_H

#include "ecs/Entity.h"
#include "math/Matrix4.h"
#include <vector>
#include <map>
#include <memory>
#include <string>

namespace tinygltf {class Model;}

namespace doriax{

    struct ObjModelData;

    struct DORIAX_API ModelComponent{
        std::shared_ptr<tinygltf::Model> gltfModel;
        std::shared_ptr<ObjModelData> objModel;

        Matrix4 inverseDerivedTransform;
        
        Entity skeleton;

        std::map<std::string, Entity> bonesNameMapping;
        std::map<int, Entity> bonesIdMapping;

        // GLTF mesh-node child entities (one per mesh-owning node when a model has several).
        // Managed exactly like bones: generated by the loader, tracked here, torn down on reload.
        std::map<int, Entity> meshNodesMapping;

        std::map<std::string, int> morphNameMapping;

        std::vector<Entity> animations;

        std::string filename;

        // Bake static multi-node GLTF meshes into this entity's MeshComponent instead of
        // generating one child entity per mesh node. This makes the model compatible with
        // same-entity features such as InstancedMeshComponent.
        bool mergeStaticMeshes = false;

        std::string loadedFilename;
        bool loadedMergeStaticMeshes = false;
        bool needUpdateModel = true;
    };

}

#endif //MODEL_COMPONENT_H
