#include "Engine.h"
#include "DoriaxSokol.h"
#include "Input.h"

#include "sokol_gfx.h"
#include "sokol_app.h"
#include "sokol_glue.h"

// 0 = windowed, 1 = maximized, 2 = fullscreen
// (sokol_app has no maximized or non-resizable window support: mode 1 falls
// back to windowed and DORIAX_WINDOW_RESIZABLE is ignored — sokol windows
// are always resizable)
#ifndef DORIAX_WINDOW_MODE
#define DORIAX_WINDOW_MODE 0
#endif

#ifndef DORIAX_WINDOW_TITLE
#define DORIAX_WINDOW_TITLE "Doriax"
#endif

#ifdef DORIAX_WINDOW_ICON
// Generated by the editor export into the project root (on the include path)
#include "app_icon.h"
#endif

static float mousePosX = 0.0f;
static float mousePosY = 0.0f;

void sokol_init(void) {
    doriax::Engine::systemViewLoaded();
    doriax::Engine::systemViewChanged();
}

void sokol_frame(void) {
    doriax::Engine::systemDraw();
}

int convMouseButtom(sapp_mousebutton mouse_button){
    if (mouse_button == SAPP_MOUSEBUTTON_LEFT){
        return D_MOUSE_BUTTON_LEFT;
    }else if (mouse_button == SAPP_MOUSEBUTTON_RIGHT){
        return D_MOUSE_BUTTON_RIGHT;
    }else if (mouse_button == SAPP_MOUSEBUTTON_MIDDLE){
        return D_MOUSE_BUTTON_MIDDLE;
    }
    return D_MOUSE_BUTTON_LEFT;
}

static void sokol_event(const sapp_event* e) {
    if (e->type == SAPP_EVENTTYPE_RESIZED){
        doriax::Engine::systemViewChanged();
    }else if (e->type == SAPP_EVENTTYPE_CHAR){
        if (e->char_code != 127) // fix macos backspace
            doriax::Engine::systemCharInput(e->char_code);
    }else if (e->type == SAPP_EVENTTYPE_KEY_DOWN){
        if (e->key_code == SAPP_KEYCODE_TAB)
            doriax::Engine::systemCharInput('\t');
        if (e->key_code == SAPP_KEYCODE_BACKSPACE)
            doriax::Engine::systemCharInput('\b');
        if (e->key_code == SAPP_KEYCODE_ENTER)
            doriax::Engine::systemCharInput('\r');
        if (e->key_code == SAPP_KEYCODE_ESCAPE)
            doriax::Engine::systemCharInput('\33'); // removed 'e' to avoid warnings
        // use same keycode of GLFW
        doriax::Engine::systemKeyDown(e->key_code, e->key_repeat, e->modifiers);
    }else if (e->type == SAPP_EVENTTYPE_KEY_UP){
        // use same keycode of GLFW
        doriax::Engine::systemKeyUp(e->key_code, e->key_repeat, e->modifiers);
    }else if (e->type == SAPP_EVENTTYPE_SUSPENDED){
        doriax::Engine::systemPause();
    }else if (e->type == SAPP_EVENTTYPE_RESUMED){
        doriax::Engine::systemResume();  
    }else if (e->type == SAPP_EVENTTYPE_MOUSE_UP){
        const bool mouseLocked = sapp_mouse_locked();
        if (!mouseLocked){
            mousePosX = e->mouse_x;
            mousePosY = e->mouse_y;
        }
        doriax::Engine::systemMouseUp(convMouseButtom(e->mouse_button), mousePosX, mousePosY, e->modifiers);
    }else if (e->type == SAPP_EVENTTYPE_MOUSE_DOWN){
        const bool mouseLocked = sapp_mouse_locked();
        if (!mouseLocked){
            mousePosX = e->mouse_x;
            mousePosY = e->mouse_y;
        }
        doriax::Engine::systemMouseDown(convMouseButtom(e->mouse_button), mousePosX, mousePosY, e->modifiers);
    }else if (e->type == SAPP_EVENTTYPE_MOUSE_MOVE){
        if (sapp_mouse_locked()){
            mousePosX += e->mouse_dx;
            mousePosY += e->mouse_dy;
        }else{
            mousePosX = e->mouse_x;
            mousePosY = e->mouse_y;
        }
        doriax::Engine::systemMouseMove(mousePosX, mousePosY, e->modifiers);
    }else if (e->type == SAPP_EVENTTYPE_MOUSE_SCROLL){
        doriax::Engine::systemMouseScroll(e->scroll_x, e->scroll_y, e->modifiers);
    }else if (e->type == SAPP_EVENTTYPE_MOUSE_ENTER){
        doriax::Engine::systemMouseEnter();
    }else if (e->type == SAPP_EVENTTYPE_MOUSE_LEAVE){
        doriax::Engine::systemMouseLeave();
    }
}

void sokol_cleanup(void) {
    doriax::Engine::systemViewDestroyed();
    doriax::Engine::systemShutdown();
}

sapp_desc sokol_main(int argc, char* argv[]) {
    (void)argc;
    (void)argv;

    sapp_desc app_desc = {0};

    app_desc.init_cb = sokol_init;
    app_desc.frame_cb = sokol_frame;
    app_desc.event_cb = sokol_event;
    app_desc.cleanup_cb = sokol_cleanup;
    app_desc.width = DEFAULT_WINDOW_WIDTH;
    app_desc.height = DEFAULT_WINDOW_HEIGHT;
    app_desc.fullscreen = (DORIAX_WINDOW_MODE == 2);
    app_desc.sample_count = 4;
    app_desc.window_title = DORIAX_WINDOW_TITLE;

#ifdef DORIAX_WINDOW_ICON
    // Window/taskbar icon on Win32 and X11, dock icon on macOS. The Windows
    // executable file icon additionally comes from app_icon.rc.
    for (int i = 0; i < DORIAX_APP_ICON_COUNT && i < SAPP_MAX_ICONIMAGES; i++) {
        app_desc.icon.images[i].width = DORIAX_APP_ICON_IMAGES[i].width;
        app_desc.icon.images[i].height = DORIAX_APP_ICON_IMAGES[i].height;
        app_desc.icon.images[i].pixels.ptr = DORIAX_APP_ICON_IMAGES[i].pixels;
        app_desc.icon.images[i].pixels.size = (size_t)DORIAX_APP_ICON_IMAGES[i].width * (size_t)DORIAX_APP_ICON_IMAGES[i].height * 4;
    }
#endif

    doriax::Engine::systemInit(argc, argv, new DoriaxSokol());

    return app_desc;
}
